#include <iostream>

int main() {
    std::cout << "Caught MyCustomException" << '\n';
    return 0;
}